# Generated by Django 4.2.1 on 2023-05-13 12:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("zip", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("state", "city", "street", "zip")},
            },
        ),
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("phone", models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARATION", "PREPARATION"),
                            ("IN TRANSIT", "IN TRANSIT"),
                            ("DELIVERED", "DELIVERED"),
                        ],
                        default="PREPARATION",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("delivered_at", models.DateField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="shipments.address",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="shipments.sender",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
