# Generated by Django 4.2.1 on 2023-05-15 18:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_address_id_alter_sender_id_alter_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=django_fsm.FSMField(default='PREPARATION', max_length=50, protected=True),
        ),
    ]
